// Shared notification feed — read by the TopBar popover and the full
// /notifications page. Frontend-only mock data (no backend).
// `read` truthy = read; omitted/false = unread.

export const NOTIFICATIONS = [
  {
    id: 'welcome',
    title: 'Welcome to Ethos',
    body: 'Your governance, compliance, and learning platform. Use the sidebar to jump into each space and the Ask button to query Ethos directly.',
    time: 'Just now',
    featured: true,
  },
  {
    id: 'assigned-journey',
    sender: 'Sarah Chen',
    title: 'Sarah Chen assigned you a Learning Journey',
    body: '"AI Governance Fundamentals" — 6 modules, due 30 June. Starts when you open it.',
    time: '1 hour ago',
    noThumbnail: true,
  },
  {
    id: 'audit-ready',
    sender: 'Mark Davies',
    title: 'Q1 2026 Audit pack ready for your review',
    body: 'Mark Davies prepared the evidence trail across 14 controls in Comply › Audit & Evidence.',
    time: '3 hours ago',
    noThumbnail: true,
  },
  {
    id: 'cpd-match',
    title: 'New CPD event matches your interests',
    body: '"Director Duties in 2026" — 2.5 points, Governance & Board Effectiveness. Tuesday at 12:00.',
    time: 'Yesterday',
    noThumbnail: true,
  },
  {
    id: 'learn',
    title: 'Introducing Learn',
    body: 'Track CPD, deliver training, and grow team capability with structured learning journeys.',
    time: '2 days ago',
    read: true,
  },
  {
    id: 'insights',
    title: 'Introducing Insights',
    body: 'Curated regulatory intelligence, news, and briefings tailored to your industry.',
    time: '4 days ago',
    read: true,
  },
  {
    id: 'comply-audit',
    title: 'New: Comply Audit & Evidence',
    body: 'Preparing for audits just got easier. Manage evidence and audit trails from a single workspace.',
    time: '1 week ago',
    read: true,
  },
  {
    id: 'ask-ethos',
    title: 'Ask Ethos got smarter',
    body: 'Better answers from your data — try the context-aware mode for more relevant responses.',
    time: '2 weeks ago',
    read: true,
  },
  {
    id: 'conflict-cleared',
    sender: 'Priya Nair',
    title: 'Priya Nair cleared a conflict you raised',
    body: 'The potential conflict on the Meridian engagement was reviewed and cleared with a note.',
    time: '2 weeks ago',
    read: true,
    noThumbnail: true,
  },
  {
    id: 'policy-due',
    title: 'Policy attestation due soon',
    body: 'Your annual sign-off on the Code of Conduct is due by 15 June. It takes about 5 minutes.',
    time: '3 weeks ago',
    read: true,
    noThumbnail: true,
  },
  {
    id: 'board-pack',
    sender: 'Mark Davies',
    title: 'Board pack published for the June meeting',
    body: '8 papers are ready in Govern › Board Papers. Pre-reading is recommended before 12 June.',
    time: '3 weeks ago',
    read: true,
    noThumbnail: true,
  },
  {
    id: 'cpd-progress',
    title: 'You\'re 70% to your annual CPD target',
    body: '21 of 30 points logged. Two upcoming events would close most of the remaining gap.',
    time: '1 month ago',
    read: true,
    noThumbnail: true,
  },
  {
    id: 'risk-assigned',
    sender: 'James Okoro',
    title: 'James Okoro assigned you a control to review',
    body: 'Control RC-114 (Vendor onboarding checks) is due for its quarterly review.',
    time: '1 month ago',
    read: true,
    noThumbnail: true,
  },
  {
    id: 'knowledge-centre',
    title: 'Introducing the Knowledge Centre',
    body: 'A single home for guidance notes, templates, and how-to articles across the platform.',
    time: '1 month ago',
    read: true,
  },
  {
    id: 'community',
    title: 'Introducing Community',
    body: 'Connect with peers, share practice, and join discussions across your industry.',
    time: '2 months ago',
    read: true,
  },
  {
    id: 'insights-weekly',
    title: 'Your weekly regulatory briefing is ready',
    body: 'Five items relevant to your industry, including two ASIC updates worth a closer look.',
    time: '2 months ago',
    read: true,
    noThumbnail: true,
  },
]
