// Map URL paths to page names (used by sidebar for active state)
export const PATH_TO_PAGE = {
  '/control': 'Control',
  '/home': 'Home',
  '/home/kanban': 'Kanban',
  '/matters': 'Work',
  '/matter/:id': 'MatterDetail',
  '/respond': 'Respond',
  '/meet': 'Meet',
  '/work/time-efficiency': 'Time & Efficiency',
  '/comply': 'Comply',
  '/comply/contracts': 'Contracts & Obligations',
  '/comply/conflicts': 'Conflict Management',
  '/comply/risk': 'Risk & Controls',
  '/comply/incidents': 'Incidents & Breaches',
  '/comply/audit': 'Audit & Evidence',
  '/comply/legislation': 'Legislation & Regulatory Landscape',
  '/comply/obligations': 'Obligations Register',
  '/govern': 'Govern',
  '/govern/meetings': 'Govern Meetings',
  '/govern/board-papers': 'Board Papers',
  '/govern/policies': 'Policies & Procedures',
  '/govern/delegations': 'Delegations of Authority',
  '/govern/company-register': 'Company Register',
  '/vault': 'Core',
  '/resources': 'Resource Library',
  '/talent': 'Talent',
  '/insights': 'Insights',
  '/learn': 'Learn',
  '/learn/journeys': 'Learning Journeys',
  '/learn/events': 'Learning Events',
  '/knowledge': 'Knowledge Centre',
  '/learn/cpd': 'CPD Tracker',
  '/learn/cpd/events': 'CPD Events',
  '/learn/skills': 'Skills Profile',
  '/community': 'Community',
  '/integrations': 'Integrations',
  '/settings': 'Settings',
  '/profile': 'Profile',
  '/notifications': 'Notifications',
  '/flags': 'Feature Flags',
  '/admin/organisation-profile': 'Admin:Organisation Profile',
  '/admin/users': 'Admin:Users',
  '/admin/privacy-security': 'Admin:Privacy & Security',
  '/admin/billing': 'Admin:Billing',
  '/admin/ai-settings': 'Admin:AI Settings',
  '/admin/integrations': 'Admin:Integrations',
  '/admin/vault': 'Admin:Vault',
  '/admin/resources': 'Admin:Resources',
  '/admin/knowledge-settings': 'Admin:Knowledge Settings',
  '/admin/talent': 'Admin:Talent',
  '/admin/activity-logs': 'Admin:Activity & Logs',
  '/admin/performance': 'Admin:Performance',
  '/admin/reporting': 'Admin:Reporting',
  '/admin/govern': 'Admin:Govern',
  '/admin/govern-settings': 'Admin:Govern Settings',
  '/admin/comply': 'Admin:Comply',
  '/admin/obligations': 'Admin:Obligations',
  '/admin/risk-framework': 'Admin:Risk Framework',
  '/admin/work': 'Admin:Work',
  '/admin/matter-types': 'Admin:Matter Types',
  '/admin/workflows': 'Admin:Workflows',
  '/admin/learning-journeys': 'Admin:Learning Journeys',
  '/admin/cpd-management': 'Admin:CPD Management',
  '/admin/cpd-regimes': 'Admin:CPD Regimes',
  '/admin/cpd-events': 'Admin:CPD Events',
  '/admin/team-capability': 'Admin:Team Capability',
  '/admin/role-profiles': 'Admin:Role Profiles',
  '/admin/knowledge-centre': 'Admin:Knowledge Centre',
}

// Reverse map: page name → path
export const PAGE_TO_PATH = Object.fromEntries(
  Object.entries(PATH_TO_PAGE).map(([path, page]) => [page, path])
)
